kebab asset keys
stactools-packages/sentinel3 pull request #13
Opened 2023-06-05 21:40 UTC by ircwaves

**Description:**
This converts all the asset keys to kebab-case.

**PR checklist:**

- [X] Code is formatted (run `scripts/format`).
- [X] Code lints properly (run `scripts/lint`).
- [X] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-06-05 22:03 UTC, gadomski requested changes
Can you add a couple of unit tests demonstrating the basic corrections? E.g. one for `aB`, one for `a_b`, and one for the special case?

2023-06-05 22:03 UTC, gadomski commented on src/stactools/sentinel3/stac.py
> +    new_asset_key = new_asset_key.lower()
```suggestion
    for first, second in zip(asset_key, asset_key[1:]):
        new_asset_key += first.lower()
        if first.islower() and second.isupper():
            new_asset_key += "-"
    new_asset_key += asset_key[-1].lower()
    new_asset_key = new_asset_key.replace("_", "-")
```

One fewer passes through the string.

2023-06-05 22:03 UTC, gadomski commented on src/stactools/sentinel3/stac.py
> +    specials = {"eopmetadata": "eop-metadata"}
Should probably be a top-level constant, in case we find more?

2023-06-07 19:24 UTC, ircwaves commented on src/stactools/sentinel3/stac.py
> +def sen3_to_kebab(asset_key):
Seems like that might be out of scope for this PR, I'll file a ticket for that.  Looks like a lot of issues when I flip the switch to `mypy.strict = true`.

2023-06-07 20:11 UTC, gadomski requested changes

2023-06-07 22:28 UTC, ircwaves commented on tests/test_stac.py
> +    assert expectation == new_keys
I had it `parametrize`d at first, but thought I was just looking for another place to use my hammer ;).

2023-06-07 23:20 UTC, gadomski approved these changes

2023-06-07 23:21 UTC, gadomski requested changes
Urgh sorry hate to do this, but let's add CHANGELOG entries so we have a record of all the junk we're moving around.

2023-06-08 12:48 UTC, ircwaves commented
> Urgh sorry hate to do this...

No sweat.  I was going to do doc and changelog last.  Actually, looks like docs are pretty scant here.  Maybe once all these changes are in, we should have a notebook update, with some verbiage to what's going on here.

2023-06-08 16:35 UTC, gadomski approved these changes

2023-06-08 16:40 UTC, merged