PC backports sentinel3: geometry cleanup
stactools-packages/sentinel3 pull request #17
Opened 2023-06-15 20:20 UTC by ircwaves

**Description:**
This builds on #15 and adds the common geometry repair strategies from PC to stactools:
- ensure counter-clockwise winding 
- handle antimeridian crossings
- round precision of geometric values to 4 decimal places

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-06-20 12:05 UTC, gadomski commented
FYI @ircwaves I'm going to hold off on a review here until #16 lands, so I can see a clean diff of this PR's changes.

2023-06-22 16:29 UTC, gadomski requested changes

2023-06-22 16:29 UTC, gadomski commented on setup.cfg
> +    antimeridian >= 0.2.3
```suggestion
    antimeridian >= 0.2.6
```

2023-06-22 16:29 UTC, gadomski approved these changes

2023-06-22 17:14 UTC, ircwaves commented on setup.cfg
> +    antimeridian >= 0.2.3
Thanks...just cribbed the mspc version.

2023-06-22 17:14 UTC, merged